package:
  name: libxshmfence-devel-cos6-x86_64
  version: 1.2

source:
  - url: http://vault.centos.org/centos/6.10/os/x86_64/Packages/libxshmfence-devel-1.2-1.el6.x86_64.rpm
    sha256: 833adacb90f00c8a58673bad0caf987872f958a60dd60605670aa6587132462d
    no_hoist: true
    folder: binary
  - url: http://vault.centos.org/6.10/os/Source/SPackages/libxshmfence-1.2-1.el6.src.rpm
    folder: source

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - libxshmfence-cos6-x86_64 ==1.2
  host:
    - libxshmfence-cos6-x86_64 ==1.2
  run:
    - libxshmfence-cos6-x86_64 ==1.2

about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libxshmfence development package"
  description: |
        X.Org X11 libxshmfence development package
