package:
  name: libxshmfence-cos6-x86_64
  version: 1.2

source:
  - url: http://vault.centos.org/centos/6.10/os/x86_64/Packages/libxshmfence-1.2-1.el6.x86_64.rpm
    sha256: 8149be38414087a25f003b86688801974fe3916b7b5c6d4a7f09e1a0fc09c6e2
    no_hoist: true
    folder: binary
  - url: http://vault.centos.org/6.10/os/Source/SPackages/libxshmfence-1.2-1.el6.src.rpm
    folder: source

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'



about:
  home: http://www.x.org
  license: MIT
  license_family: MIT
  summary: "(CDT) X.Org X11 libxshmfence runtime library"
  description: |
        X.Org X11 libxshmfence runtime library
